services:
  backend:
    build: /backend
    environment:
      - WEATHER_API_KEY=79f6e969ab6ec49baa65d9f36f6b4071
    ports:
      - "3000:3000"
  
  frontend:
    build: /frontend
    ports:
      - "8080:80"
      