services:
  backend:
    build: /backend
    environment:
      - WEATHER_API_KEY=<YOUR API WEATHER_API_KEY>
    ports:
      - "3000:3000"
  
  frontend:
    build: /frontend
    ports:
      - "8080:80"
      