version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - WEATHER_API_KEY=/run/secrets/weather_api_key
    ports:
      - "3000:3000"
    secrets:
      - weather_api_key

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"

secrets:
  weather_api_key:
    file: ./api_key.txt
